version: '3.8'

services:
  # ====================================================
  # BACKEND (NODE API)
  # ====================================================
  backend:
    image: cardapio-backend:latest
    # Em produção, comente o build se for usar imagem de registry
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL_FILE: /run/secrets/db_connection_string
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      # URLs corrigidas
      FRONTEND_URL: https://kicardapio.towersfy.com
      ADMIN_URL: https://kicardapio.towersfy.com
      API_URL: https://apikicardapio.towersfy.com
      ALLOWED_ORIGINS: "*"
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - gestao_network   # Rede única para tudo (Traefik e Postgres)
    secrets:
      - db_connection_string
      - jwt_secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Roteamento da API (Domínio Correto: apikicardapio.towersfy.com)
        - "traefik.http.routers.backend.rule=Host(`apikicardapio.towersfy.com`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.backend.tls.domains[0].main=towersfy.com"
        - "traefik.http.routers.backend.tls.domains[0].sans=*.towersfy.com"
        - "traefik.http.services.backend.loadbalancer.server.port=3001"
        - "traefik.http.routers.backend.priority=1000"
        # Roteamento de Uploads
        - "traefik.http.routers.backend-uploads.rule=Host(`apikicardapio.towersfy.com`) && PathPrefix(`/uploads`)"
        - "traefik.http.routers.backend-uploads.entrypoints=websecure"
        - "traefik.http.routers.backend-uploads.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.backend-uploads.priority=1000"

  # ====================================================
  # FRONTEND ADMIN (PAINEL DO DONO)
  # ====================================================
  frontend-admin:
    image: cardapio-admin:latest
    build:
      context: .
      dockerfile: frontend/admin/Dockerfile
      args:
        - VITE_API_URL=/api
    networks:
      - gestao_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Acesso principal do sistema (Dashboard)
        - "traefik.http.routers.admin.rule=Host(`kicardapio.towersfy.com`) || Host(`admin.kicardapio.towersfy.com`)"
        - "traefik.http.routers.admin.entrypoints=websecure"
        - "traefik.http.routers.admin.tls=true"
        - "traefik.http.routers.admin.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.admin.tls.domains[0].main=towersfy.com"
        - "traefik.http.routers.admin.tls.domains[0].sans=*.towersfy.com"
        - "traefik.http.services.admin.loadbalancer.server.port=80"
        - "traefik.http.routers.admin.priority=1000"

  # ====================================================
  # FRONTEND CLIENT (LOJAS / TABLETS)
  # ====================================================
  frontend-client:
    image: cardapio-client:latest
    build:
      context: .
      dockerfile: frontend/client/Dockerfile
      args:
        - VITE_API_URL=/api
    networks:
      - gestao_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Regra simplificada e robusta para subdomínios de lojas
        - "traefik.http.routers.client.rule=HostRegexp(`[a-z0-9-]+\\.towersfy\\.com`) && !Host(`container.towersfy.com`, `kicardapio.towersfy.com`, `apikicardapio.towersfy.com`, `admin.kicardapio.towersfy.com`)"
        - "traefik.http.routers.client.entrypoints=websecure"
        - "traefik.http.routers.client.tls=true"
        - "traefik.http.routers.client.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.client.tls.domains[0].main=towersfy.com"
        - "traefik.http.routers.client.tls.domains[0].sans=*.towersfy.com"
        - "traefik.http.services.client.loadbalancer.server.port=80"
        - "traefik.http.routers.client.priority=1"

volumes:
  uploads_data:

networks:
  gestao_network:
    external: true

secrets:
  db_connection_string:
    external: true
  jwt_secret:
    external: true