version: '3.8'

services:
  # ====================================================
  # BACKEND (NODE API)
  # ====================================================
  backend:
    image: cardapio-backend:latest
    # Em produção, comente o build se for usar imagem de registry
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      # Conexão com o serviço 'postgres' da stack de banco (nome do serviço no swarm)
      # Formato: postgresql://<user>:<pass>@<service_name>:5432/<db_name>
      DATABASE_URL_FILE: /run/secrets/db_connection_string
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      # URLs para CORS e Redirecionamentos
      FRONTEND_URL: https://kicardapio.towersfy.com # URL do Painel Admin/SaaS
      ADMIN_URL: https://kicardapio.towersfy.com
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - gestao_network   # Rede única para tudo (Traefik e Postgres)
    secrets:
      - db_connection_string
      - jwt_secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Roteamento da API (Prioridade Alta para não conflitar com lojas)
        - "traefik.http.routers.backend.rule=Host(`api.kicardapio.towersfy.com`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.backend.loadbalancer.server.port=3001"
        - "traefik.http.routers.backend.priority=100"
        # Roteamento de Uploads
        - "traefik.http.routers.backend-uploads.rule=Host(`api.kicardapio.towersfy.com`) && PathPrefix(`/uploads`)"
        - "traefik.http.routers.backend-uploads.entrypoints=websecure"
        - "traefik.http.routers.backend-uploads.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.backend-uploads.priority=100"

  # ====================================================
  # FRONTEND ADMIN (PAINEL DO DONO)
  # ====================================================
  frontend-admin:
    image: cardapio-admin:latest
    build:
      context: .
      dockerfile: frontend/admin/Dockerfile
    networks:
      - gestao_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Acesso principal do sistema (Dashboard)
        - "traefik.http.routers.admin.rule=Host(`kicardapio.towersfy.com`) || Host(`admin.kicardapio.towersfy.com`)"
        - "traefik.http.routers.admin.entrypoints=websecure"
        - "traefik.http.routers.admin.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.admin.loadbalancer.server.port=80"
        - "traefik.http.routers.admin.priority=100"

  # ====================================================
  # FRONTEND CLIENT (LOJAS / TABLETS)
  # ====================================================
  frontend-client:
    image: cardapio-client:latest
    build:
      context: .
      dockerfile: frontend/client/Dockerfile
    networks:
      - gestao_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gestao_network"
        # Regra universal para qualquer subdomínio em towersfy.com, exceto serviços do sistema
        - 'traefik.http.routers.client.rule=HostRegexp(`^(?!(container|admin|api|kicardapio|www|api\.kicardapio)$)[a-z0-9-]+\.towersfy\.com`)'
        - "traefik.http.routers.client.entrypoints=websecure"
        - "traefik.http.routers.client.tls=true"
        - "traefik.http.routers.client.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.client.loadbalancer.server.port=80"
        - "traefik.http.routers.client.priority=1"

volumes:
  uploads_data:

networks:
  gestao_network:
    external: true

secrets:
  db_connection_string:
    external: true
  jwt_secret:
    external: true