-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "productionArea" TEXT DEFAULT 'Cozinha';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "ncm" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "cfop" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "cest" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "measureUnit" TEXT DEFAULT 'UN';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "origin" INTEGER DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "taxPercentage" DOUBLE PRECISION DEFAULT 0;
